### PR TITLE
add rhel8 support

### PR DESCRIPTION
**Pull request by mjourdan**
Hi,

Two issues prevented this role to work on RHEL8 and derivatives. The following fixes issues #7 and #8.

### CODE REVIEW

**Comment by mjourdan** [comment]
Hello @gardouille, any news on this?

**Comment by gardouille** [comment]
Sorry… Looking this and testing today ! Thanks.

**Comment by gardouille** [comment]
(still) working fine with Debian base and i can only trust you for RHEL support :)

Merging and publishing a new version by this afternoon. Thank you for your contribution :+1:

**Comment by mjourdan** [comment]
Thank you!

**Pull request merged**
